### ISSUE TITLE
No response, response and responseCode does not show change after sample program is executed

### ISSUE THREAD

**Issue by YKou-Kody** [fbarresi/BeckhoffHttpClient#14]
Hello! I'm looking to utilize this library in one of our Twincat programs, and right now I'm just trying to get started with this library. 

I've copied over the code in the readme to test out a simple API call on my local computer (not PLC) , but I'm not getting any responses.
My code is as shown below:

`Main`:
```PROGRAM MAIN
VAR
	
	bError: BOOL;
	udiErrorId : UDINT;
	client : HttpClient;
END_VAR
```

```
client(
	Execute:=FALSE ,
	Address:= 'https://dog.ceo/api/breeds/image/random',
	CallMethod:= 'GET' ,
	Body:= '',
	ResponseCode:= 'Global_Variables.ResponseCode',
	Response:= 'Global_Variables.ResponseBody',
	HasError=> bError,
	ErrorId=> udiErrorId);
```

```
Global_Variables (under GVL):`
`VAR_GLOBAL
	ResponseCode: INT;
	ResponseBody : JsonRadioStatus;
END_VAR
```

After starting the program, the response body and response both do not change as they are expected to. I've also tried out the sample project existing in this repository by cloning it, and the same goes for that project, I'm getting no errors and no responses. 

Could you please enlighten me as to what could be possibly causing this? Thank you so much, and thanks so much for the work on this library.

**Comment by fbarresi** [comment]
Hi!

Did you already installed the [latest version](https://github.com/fbarresi/BeckhoffHttpClient/releases/tag/1.0.31) of the unofficial Twicat function on your target/test machine? No matter if it is a PLC or not. 

Best regards, 
FB

**Comment by YKou-Kody** [comment]
Hello, thanks for the quick response! 

Unfortunately, I did have TFU001 installed, still no results thus far after reinstalling as well. 

Thanks,

KK

**Comment by YKou-Kody** [comment]
Hello,

Ended up figuring out that it's because I had `execute` set to False instead of True, got 200 after :)

**Comment by fbarresi** [comment]
Nice! Happy to hear that you find out the problem.
Best regards.
FB

**Comment by YKou-Kody** [comment]
@fbarresi Hi again!

So it turns out, the library is not functioning on my existing twincat project, the exact same code was copied over from the sample project which had everything working properly, but the client does not make any calls and ResponseCode remains 0 inside `Global_Variables`. Now that I have the sample project working fine I can confirm `TFU001` is installed successfully and the library is referenced properly as well, do you have any idea as to what could be causing this? I have the same set up on both twincat projects.

Thanks so much,

KK
