### ISSUE TITLE
Hide Console window

### ISSUE THREAD

**Issue by ramonneves** [fbarresi/BeckhoffHttpClient#5]
Hello! It is me again...

Is there a way to hide permanently the console window that shows up every http command? 
I was looking in the TFU code and you could maybe implement a variable to enable or disable the LOG window. 

Thanks!

**Comment by fbarresi** [comment]
https://github.com/fbarresi/BeckhoffHttpClient/tree/1.0.19

**Comment by fbarresi** [comment]
Solved in v. [1.0.19](https://github.com/fbarresi/BeckhoffHttpClient/releases/1.0.19)
