### ISSUE TITLE
Use this Library for make notification (Pushover.net)

### ISSUE THREAD

**Issue by elconfa** [fbarresi/BeckhoffHttpClient#7]
Hello, I would like to ask for help in order to use this library to generate notifications via the PushOver service (https://pushover.net/api)

**Comment by fbarresi** [comment]
Hi, 
Please excuse me, I forgot to reply you.
do you still need help? 
I provided in the repository an [example](https://github.com/fbarresi/BeckhoffHttpClient/tree/master/TwincatConsoleProject) of a plc application using this library.

the software is really easy to use:
* [Download](https://github.com/fbarresi/BeckhoffHttpClient/releases/download/1.0.25/TFU001_BeckhoffHttpClient.msi) and install the Twincat Function on your target system
* define you datatype in form of DUT and [provide attributes](https://github.com/fbarresi/BeckhoffHttpClient#the-json-attribute) for a Json conversion like described [here](https://pushover.net/api#tldr)
* download the [BeckhoffHttpClient.library](https://github.com/fbarresi/BeckhoffHttpClient/releases/download/1.0.25/BeckhoffHttpClient.library) and reference it in your plc project
* call the client in your software like [here](https://github.com/fbarresi/BeckhoffHttpClient#reference-the-beckhoffhttpclient-library)

**Comment by Discus2c** [comment]
Hi,
 Thanks for a quick answer. I will play with it some more over the weekend and publish my findings.

**Comment by massimo-pizzardi** [comment]
> Hi,
> Thanks for a quick answer. I will play with it some more over the weekend and publish my findings.

Were you able to test? I don't have enough experience and I can't figure it out ...

**Comment by Discus2c** [comment]
Hey Massimo,
   No I could not get it to work - on my laptop. Maybe there is some
program preventing the rest api program from starting on my machine, dunno.
 I played around with the Beckhoff version of rest api calls and was able
to get them to work. I wanted to place this on a Beckhoff PLC, but right
now just dont have the time.

**Comment by fbarresi** [comment]
closed due to inactivity
