### ISSUE TITLE
Running on a local machine

### ISSUE THREAD

**Issue by Discus2c** [fbarresi/BeckhoffHttpClient#8]
Im having issues trying to run this on a local machine Win10x64 machine... 
Does this have to run on Beckhoff Win 10 IoT machine?
The TFU0001.exe module is located in the right folder, code it pointing to it, but I dont think it is running when executed. Any ideas?

**Comment by fbarresi** [comment]
Hi, 
It would be interesting to see what is telling the log file.
Put the [config file](https://github.com/fbarresi/BeckhoffHttpClient/blob/master/TFU001/TFU001/log.config) in the exe folder. 
Try to call the software from the plc and look at the log file.
You can also post the whole log file here.

**Comment by fbarresi** [comment]
This software doesn't need to run in a win 10 iot distribution. It was tested locally on normal win7/win10 plcs.

Please note that the software also doesn't have any graphic. You could just see over the task manager that a new background process starts.

**Comment by fbarresi** [comment]
closed due to inactivity
